### ISSUE TITLE
Run "make test" when compiling interpreter

### ISSUE THREAD

**Issue by duggelz** [GoogleCloudPlatform/python-runtime#107]
I thought we did this already, but we don't, except indirectly as part of the profile-guided optimization.

**Comment by jonparrott** [comment]
Do we need to do anything above and beyond what PGO does?

**Comment by duggelz** [comment]
Technically those tests are run by a differently compiled binary, so we should run them again with the final binary.

**Comment by jonparrott** [comment]
Gotcha.

**Comment by duggelz** [comment]
Also, when run as part of PGO, test failures are ignored.

Special call out to asyncio, we should make sure it works properly on Python 3.6.
