### ISSUE TITLE
Add Python 3.6.1 interpreter to image

### ISSUE THREAD

**Issue by duggelz** [GoogleCloudPlatform/python-runtime#108]

**Comment by ToGoBananas** [comment]
+1

**Comment by duggelz** [comment]
#104

**Comment by duggelz** [comment]
Need to incorporate this fix from upstream:

https://github.com/python/cpython/commit/a1054c3b0037d4c2a5492e79fc193f36245366c7

**Comment by ToGoBananas** [comment]
@duggelz thanks for update, but python 3.6 still unavailable in eu.gcr.io/google_appengine/python:latest
Can you add it?

**Comment by ToGoBananas** [comment]
I was able to build this image manually using this repo, thanks

**Comment by duggelz** [comment]
#110 #113 #114

**Comment by duggelz** [comment]
Image released, see release notes: 
https://github.com/GoogleCloudPlatform/python-runtime/releases/tag/2017-05-14-142425
