### ISSUE TITLE
Figure out Python 3.6 and openssl deprecation

### ISSUE THREAD

**Issue by duggelz** [GoogleCloudPlatform/python-runtime#111]
The Python 3.6 documentation says building with OpenSSL 1.0.1 is deprecated.  Figure out what this means, and what we need to do about it.

https://docs.python.org/3/library/ssl.html

**Comment by jonparrott** [comment]
We should probably just compile openssl latest from source, yeah?

**Comment by ezarowny** [comment]
Any updates on this?

**Comment by duggelz** [comment]
Upon investigation, nothing currently needs to be done for 3.6, but will for 3.7.  The next major update of the base OS image updates openssl to 1.0.2 or greater, which will resolve this issue.
