### ISSUE TITLE
Alpine based branch

### ISSUE THREAD

**Issue by AdamMagaluk** [GoogleCloudPlatform/python-runtime#120]
Any plans or thoughts on providing an alpine based image to allow for smaller image sizes?

Size comparisons:

**gcr.io/google-appengine/python**: 808 MB
**python:alpine**: 89.4 MB

**Comment by jonparrott** [comment]
This would be somewhat difficult, as Alpine uses muslc and [manylinux1](https://www.python.org/dev/peps/pep-0513/#the-manylinux1-policy) requires glibc. If we have an alpine branch, we'll have to pull in basically all of build dependencies which will likely make the image size around the same as our current image.

**Comment by duggelz** [comment]
We are looking into a couple of possible ways to decrease image size.
- Alpine as mentioned
- Removing the build tools from the runtime images
- Splitting up the monolithic base image into individual images for each interpreter version
- Giving users finer control over which Debian packages installed
- Distroless (from scratch) images: https://github.com/GoogleCloudPlatform/distroless

**Comment by duggelz** [comment]
Closing this.  Although a laudable idea, we have no immediate plans to do this.
