### ISSUE TITLE
Outdated `setuptools` causing package installation issues

### ISSUE THREAD

**Issue by kyleobrien91** [GoogleCloudPlatform/python-runtime#152]
Installing `python-memcached==1.58` inside app engine started breaking for me today.

Running `gcloud app deploy` gives decent output up until the installation of `python-memcached`

The following output is what I get at that point

<img width="734" alt="screen shot 2017-10-04 at 22 15 19" src="https://user-images.githubusercontent.com/2432944/31198224-cbb216e4-a953-11e7-8dc0-d58ea83a4966.png">

This fails on the docker build step `RUN pip install -r requirements.txt`

Upgrading setuptools to `setuptools-36.5.0` fixed this problem. If I replicate the Docker build steps that run for app engine but add a line `RUN pip install -U pip setuptools` before running the `pip install` above, this is resolved completely.

This is the related issue in the `python-memcached` repo - https://github.com/linsomniac/python-memcached/issues/103

How would we tackle this? Is it an option to upgrade the setuptools version? Do we pin it to a version? Or do you think it's acceptable keeping a broad version unpinned upgrade?

**Comment by kyleobrien91** [comment]
Can I submit a PR for this? Or do you not agree with the approach?

**Comment by duggelz** [comment]
Can you verify that this problem is fixed for you now?

**Comment by duggelz** [comment]
Appears to be fixed, closing:

```shell
$ docker run -it --entrypoint=/bin/bash gcr.io/google-appengine/python
root@56d393372fca:/home/vmagent/app# virtualenv -p python3.6 ~/env
Running virtualenv with interpreter /opt/python3.6/bin/python3.6
Using base prefix '/opt/python3.6'
New python executable in /root/env/bin/python3.6
Also creating executable in /root/env/bin/python
Installing setuptools, pip, wheel...done.
root@56d393372fca:/home/vmagent/app# . ~/env/bin/activate
(env) root@56d393372fca:/home/vmagent/app# pip install python-memcached
Collecting python-memcached
  Downloading python-memcached-1.58.tar.gz
Collecting six>=1.4.0 (from python-memcached)
  Downloading six-1.11.0-py2.py3-none-any.whl
Building wheels for collected packages: python-memcached
  Running setup.py bdist_wheel for python-memcached ... done
  Stored in directory: /root/.cache/pip/wheels/16/75/11/86f65dfdcfcfbdaee336d5a3c125b5ac1c53973c4515c77ef5
Successfully built python-memcached
Installing collected packages: six, python-memcached
Successfully installed python-memcached-1.58 six-1.11.0
(env) root@56d393372fca:/home/vmagent/app# 
```

**Comment by EdNutting** [comment]
Hi,

This is still causing an issue. Setuptools is now stuck at version 36, and for "dj-stripe@master" I need version 38. How can I override the version built into the image? Is there a way to run two "pip install", 1st one to upgrade setuptools, second one to install my requirements.txt?

Many thanks,
Ed

**Comment by duggelz** [comment]
I will refresh setuptools with the next image update.  Meanwhile, you can try adding `setuptool==38.5.0` to your requirements.txt.  Sometimes this works, depending on where in the install process the new setuptools is needed (i.e. it doesn't work if the new setuptools changes how requirements specs are parsed).

**Comment by duggelz** [comment]
New image released.
