### ISSUE TITLE
Switch from using local docker to Container Builder

### ISSUE THREAD

**Issue by dlorenc** [GoogleCloudPlatform/python-runtime#29]
This should be as simple as switching "docker build" in the Makefile to:

`gcloud alpha container builds create . -t $IMAGE_NAME`.

**Comment by jonparrott** [comment]
@dlorenc this will work for the top-level runtime, but we have a sub-build that builds the Python 3.5 interpreter. Unfortunately, we have to use docker run to extract the build artifact:

https://github.com/GoogleCloudPlatform/python-runtime/tree/master/python-interpreter-builder

Any ideas on that one?

**Comment by dlorenc** [comment]
Hey,

This should be pretty easy using a cloudbuild.yaml file. Container Builder supports multi-step builds, and the `/workspace` directory is preserved between them. Each step is defined as a docker image and a command to run inside that image.

So for this one it could look like:

step 1:
build an intermediate image from the debian base, adding in everything you need to build the python interpreter, but don't actually build it
 step 2:
inside that intermediate image, run a command to build the python interpreter tarball, place it in /workspace
step 3:
build the final image, adding in the interpreter tarball

Note you could collapse steps 1 and 2 by building and publishing a "builder image", but then you'd need a release process for that too :)

**Comment by dlorenc** [comment]
Here's an example where we do something almost identical:
https://github.com/GoogleCloudPlatform/debian-docker/blob/master/cloudbuild.yaml.in

The first step uses a builder image that has docker ready, and it builds a second intermediate builder image that has everything it needs to build a debian base.

The second step actually builds a debian base tarball inside that intermediate image.

The third step builds our final image from that tarball

**Comment by jonparrott** [comment]
@dlorenc cool, one more question: we have several docker-based [tests](https://github.com/GoogleCloudPlatform/python-runtime/tree/master/tests) that use a locally built version of the runtime as the base. Do you have any recommendations for those?

**Comment by dlorenc** [comment]
Cool! When do you typically run these tests? Pre-commit to github, before a release, continuously?

**Comment by jonparrott** [comment]
@dlorenc yes. :)

**Comment by dlorenc** [comment]
Haha. I'll grab some time to chat with you. We're working on environments for running each type of test (pre-commit, pre-release and CI), but they'll probably end up looking a little bit different from each other.
