### ISSUE TITLE
Get Unrecognized directory type when: gcloud beta app gen-config --custom

### ISSUE THREAD

**Issue by garywu** [GoogleCloudPlatform/python-runtime#31]
Trying to follow the readme to generate default configs:

```
$ gcloud beta app gen-config --custom
ERROR: (gcloud.beta.app.gen-config) Unrecognized directory type: [/Users/admin/test]
```

The directory is empty and writable

**Comment by jonparrott** [comment]
You need to at least have an app.yaml with runtime: python specified. Gen
config custom reads the existing config and generates a custom runtime from
it.

**Comment by garywu** [comment]
the requirement of app.yaml is not mentioned in any of the places that document this command. And it does not work:
```
$ cat app.yaml
runtime: python
vm: true
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  # You can also specify 2 for Python 2.7
  python_version: 2
$ gcloud beta app gen-config --custom
ERROR: (gcloud.beta.app.gen-config) Unrecognized directory type: [/Users/admin/test]
```

but having an empty py file in a directory (no app.yaml or other files) works, i.e.:
```
touch empty.py
gcloud beta app gen-config --custom
This looks like a Python app.  If so, please enter the command to run
the app in production (enter nothing if it's not a python app): :
```

**Comment by jonparrott** [comment]
Gotcha. I'll update the README. Is there any reason you're using `gen-config` instead of writing the dockerfile yourself?
