### ISSUE TITLE
Dockerfile FROM caching

### ISSUE THREAD

**Issue by duggelz** [GoogleCloudPlatform/python-runtime#58]
This statement

    FROM gcr.io/google_appengine/debian8

Isn't guaranteed to pull in the latest image from GCR.  I believe it just uses the latest image that happens to be on the local Docker daemon.

**Comment by jonparrott** [comment]
Don't we build with docker caching disabled?

**Comment by nkubala** [comment]
`--no-cache` is passed as a flag to `docker build` through the cloudbuild.yaml.

https://github.com/GoogleCloudPlatform/python-runtime/blob/master/cloudbuild.yaml.in#L8

**Comment by duggelz** [comment]
Caching is enabled when building locally.  I'm going to disable it by default.  And/or just stop building locally.

Also I'm running into #59, referencing 'google_appengine' in one place and 'google-appengine' in another.

**Comment by duggelz** [comment]
It looks like we should also pass in '--pull', unless cloudbuild does this automagically.

**Comment by duggelz** [comment]
Also, --pull is implicit during cloudbuild, so we don't need to update the cloudbuild.yaml.in
