### ISSUE TITLE
Audit dash vs underscore everywhere

### ISSUE THREAD

**Issue by duggelz** [GoogleCloudPlatform/python-runtime#59]
Docker image names sometimes treat - and _ the same, and sometimes not.  We should pick one and always use it everywhere.  For example:

    $ docker images gcr.io/google-appengine/debian8:latest
    REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
    gcr.io/google-appengine/debian8   latest              bce67a0a288d        2 weeks ago         128.1 MB

    $ docker images gcr.io/google_appengine/debian8:latest
    REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
    gcr.io/google_appengine/debian8   latest              9e348dc9669e        3 months ago        128 MB

**Comment by nkubala** [comment]
I think we have plans to change this to a different name entirely? cc @dlorenc

**Comment by dlorenc** [comment]
We should prefer the hyphens. Underscores are equivalent, but they're a legacy feature that isn't needed anymore. I can explain more if anyone is interested.
