### ISSUE TITLE
UPLOAD_TO_STAGING doesn't work

### ISSUE THREAD

**Issue by duggelz** [GoogleCloudPlatform/python-runtime#61]
Output from Jenkins running jenkins_build.sh:

```
2017-01-04_22_14: digest: sha256:7cc23e7e489c798a67147b69d076c1667b0f4281b6f8c174f8571faf63230721 size: 33663
DONE
--------------------------------------------------------------------------------

ID                                    CREATE_TIME                DURATION  SOURCE                                                                                                             IMAGES                                           STATUS
04473501-50b4-4d1a-ae71-2869c2b665f5  2017-01-04T22:14:43+00:00  39M53S    gs://vm-runtime-deployment-qa_cloudbuild/source/1483568064.66_gcr.io_google_appengine_python:2017-01-04_22_14.tgz  gcr.io/google_appengine/python:2017-01-04_22_14  SUCCESS
Untagged: gcr.io/google_appengine/python:staging
Error response from daemon: could not find image: no such id: gcr.io/google_appengine/python:2017-01-04_22_14
Build step 'Execute shell' marked build as failure
Sending e-mails to: jonwayne@google.com dgreiman@google.com
Finished: FAILURE
```

I can manually tag by pulling the image from GCR to local, tagging it locally, and pushing it back to GCR.  Surely there is a better way.

    gcloud docker -- pull gcr.io/google-appengine/python:2017-01-04_22_14
    gcloud docker -- tag gcr.io/google-appengine/python:2017-01-04_22_14 gcr.io/google-appengine/python:staging
    gcloud docker -- push gcr.io/google-appengine/python:staging

**Comment by duggelz** [comment]
Actually, it looks like the new internal workflow handles the 'staging' tags as well as 'latest'?  So maybe we should just remove the UPLOAD_TO_STATING functionality here.

**Comment by nkubala** [comment]
I left the `UPLOAD_TO_STAGING` functionality in this script when I checked it in as `jenkins_build.sh` (I didn't write this); but you are correct, the way we're tagging/releasing images implicitly stages every image before releasing them, so I don't think we need it anymore.

**Comment by duggelz** [comment]
#65
