### ISSUE TITLE
Build interpreters with make -j and see if it's faster

### ISSUE THREAD

**Issue by duggelz** [GoogleCloudPlatform/python-runtime#92]
Building the interpreters is slow.  It'd be nice to use `make -j<num_jobs>` to build with more cores. 
 We'd have to make sure it: 1) still produces correct results, 2) is actually faster, 3) what's the right value of `num_jobs`.

Currently Container Builder uses a single core VM for building, but is rolling out support for larger machine sizes, so we'll have to request an 8 or 32 core machine in cloudbuild.yaml to actually get a benefit.

**Comment by duggelz** [comment]
Most of the time is spent in the single-threaded profile generation, so this turns out to not be that much faster.  About 1.35x speedup in the best case (48 cores).

On 48 core machine:
```
time make profile-opt:
real	20m16.184s
user	13m44.396s
sys	1m31.088s
```

```
time make -j48 profile-opt
real	15m0.466s
user	13m17.516s
sys	4m33.380s
```

**Comment by duggelz** [comment]
For comparison, compile time without PGO:
```
time make altinstall
real	2m52.044s
user	2m24.536s
sys	0m16.376s
```
```
time make -j48 altinstall
real	0m43.948s
user	2m18.156s
sys	0m19.584s
```

**Comment by duggelz** [comment]
Apparently, make -j48 can also cause the build to randomly fail and/or produce corrupt binary files.

**Comment by jonparrott** [comment]
Yikes.
